<?php

return [
    'name' => 'TestFlight APP',
    'beian' => '',
    'cdnurl' => '',
    'version' => '1.0.1',
    'timezone' => 'Asia/Shanghai',
    'forbiddenip' => '',
    'languages' => [
        'backend' => 'zh-cn',
        'frontend' => 'zh-cn',
    ],
    'fixedpage' => 'app',
    'categorytype' => [],
    'configgroup' => [
        'config' => '全局配置',
        'imap' => '邮局服务器',
        'basic' => 'Basic',
        'email' => 'Email',
        'dictionary' => 'Dictionary',
    ],
    'mail_type' => '2',
    'mail_smtp_host' => 'mail.testflight.wiki',
    'mail_smtp_port' => '25',
    'mail_smtp_user' => 'test@testflight.wiki',
    'mail_smtp_pass' => 'Ly123456',
    'mail_verify_type' => '2',
    'mail_from' => 'test@testflight.wiki',
    'config_url' => 'https://weidafir.com',
    'config_down_urls' => 'https://weidafir.com',
    'imap_host' => 'mail.testflight.wiki',
    'imap_port' => '143',
    'imap_user' => 'admin@testflight.wiki',
    'imap_pass' => 'Ly123456',
    'config_domain' => 'testflight.wiki',
    'config_validity' => '5000',
    'config_update_count' => '20',
    'config_desc' => '新模式TestFlight上架，苹果官方认可，零风险，分发再无忧，远离APP频繁掉签，远离其他方式高价钱，无需信任直接安装，无限量下载和更新。',
];
